sudo: required
language: android
jdk: oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

env:
 global:
 - ANDROID_API=27
 - ANDROID_BUILD_TOOLS=26.1.1 #Latest release (Sept 2017)
 - ADB_INSTALL_TIMEOUT=10 # ADB connection timeout set to 10 mins

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install latest Android SDK tools
    - platform-tools
    - build-tools-26.1.1
    - android-27
    - extra
before_install:
  - yes | sdkmanager "platforms;android-27"
script:
   - chmod +x ./Nutrivis/gradlew
   - ./Nutrivis/gradlew clean build # build project from scratch
   # - ./Nutrivis/gradlew build connectedCheck (Will use when test cases exist)
      # build, run assemble, check + possible tests
